### ISSUE TITLE
"Interested in what makes us tick" link not working

### ISSUE THREAD

**Issue by carkod** [canonical/global-nav#233]
Maybe replace the [current link](https://canonical.com/careers/engineering#available-roles) with https://canonical.com/careers/all?filter=Engineering

![image](https://user-images.githubusercontent.com/14939793/203330738-27396135-a8fb-4751-b71e-48d98cb78a35.png)

**Comment by suryakanthrai** [comment]
Hiii @carkod 

can you please add the screen shot for it i am not able to see it in the above links
