### ISSUE TITLE
Seperators are too thick between items

### ISSUE THREAD

**Issue by petesfrench** [canonical/global-nav#260]
The separators are supposed to be a lot tinner, something like  `hsla(0, 0%, 100%, .1)` as seen on https://global-nav-259.demos.haus/

**Comment by egezeytun** [comment]
@mtruj013 @juanruitina @lyubomir-popov does this concern the global nav at c.com? 

Pete asked me where to create an issue for this. I am thinking perhaps we can create a second epic for c.com refresh and put everything we want to do after going live there. Let me know if these are separate.

**Comment by egezeytun** [comment]
Thanks @juanruitina I was confused. @petesfrench can you create an issue for this in the meganav epic you are working in?

**Comment by petesfrench** [comment]
Sure! But this isn't part of the meganav work, this is just a general global-nav maintenance issue?
